NAME := Sed_is_for_losers

# ---------------------------------------------------------#
#                       DIRECTORIES                        #
# ---------------------------------------------------------#

SRCS_DIR := 

# ---------------------------------------------------------#
#                       SOURCE FILES                       #
# ---------------------------------------------------------#

SRCS_PHONE :=	main.cpp

# ---------------------------------------------------------#
#                       BUILD SOURCE                       #
# ---------------------------------------------------------#

SRCS =	$(addprefix $(SRCS_DIR), $(SRCS_PHONE)) \

# ---------------------------------------------------------#
#                         HEADERS                          #
# ---------------------------------------------------------#

HEAD_DIR := includes/

CPPFLAGS += $(addprefix -I, $(HEAD_DIR))

# ---------------------------------------------------------#
#                           LIBS                           #
# ---------------------------------------------------------#

LIBS_DIR :=

LIBS_TARGET :=

LIBS_NAMES := $(patsubst %.a,%,$(notdir $(LIBS_TARGET)))

LIBS_INCLUDES := $(addprefix $(LIBS_DIR), $(addsuffix /includes,$(LIBS_NAMES))) # si pas de /include ajouter manuellement

CPPFLAGS += $(addprefix -I, $(LIBS_INCLUDES))

SYS_LIBS = m X11 Xext
SYS_LIBS := $(addprefix -l, $(SYS_LIBS))

# ---------------------------------------------------------#
#                           OBJS                           #
# ---------------------------------------------------------#

BUILD_DIR := .build/

OBJS_DIR := $(addprefix $(BUILD_DIR), objs/)
OBJS := $(addprefix $(OBJS_DIR), $(notdir $(SRCS:.cpp=.o)))

# ---------------------------------------------------------#
#                           DEPS                           #
# ---------------------------------------------------------#

DEPS := $(OBJS:.o=.d)

CPPFLAGS += -MMD -MP

# ---------------------------------------------------------#
#                   CONFIG COMPILATION                     #
# ---------------------------------------------------------#

CFLAGS += -g3 -std=c++98 -Wall -Wextra -Werror

CC = c++

# ---------------------------------------------------------#
#                           MOD                            #
# ---------------------------------------------------------#

ifeq ($(MOD), debug)
	CFLAGS += -g3
endif

# ---------------------------------------------------------#
#                          RULES                           #
# ---------------------------------------------------------#

all: $(NAME)

$(NAME): $(LIBS_TARGET) $(OBJS)
	$(CC) $^ -o $@ $(SYS_LIBS)

$(OBJS_DIR)%.o: $(SRCS_DIR)%.cpp
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<

$(LIBS_TARGET): force
	$(MAKE) -C $(dir $@)

force:

# ---------------------------------------------------------#
#                       CLEAN                              #
# ---------------------------------------------------------#

clean:
	rm -rf $(BUILD_DIR)
	$(foreach lib,$(LIBS_TARGET),$(MAKE) -C $(dir $(lib)) clean;)

fclean: clean
	rm -rf $(NAME)
	$(foreach lib,$(LIBS_TARGET),$(MAKE) -C $(dir $(lib)) fclean;)

re:
	$(MAKE) fclean
	$(MAKE) all

.PHONY : clean fclean all re force

-include $(DEPS)
